name: lazy_lumberdash
description: Lumberdash abstraction that lazily dispatches log calls, either periodically or stack size.
version: 0.0.3
homepage: https://github.com/dart-pacotes/lazy_lumberdash

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  lumberdash: ^3.0.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
  mocktail:
