name: lazy_lumberdash
description: Lumberdash abstraction that lazily dispatches log calls, either periodically or stack size.
version: 0.0.1
author: freitzzz
homepage: https://github.com/freitzzz/lazy_lumberdash

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  lumberdash: ^2.1.1

dev_dependencies:
  effective_dart: 1.2.4
  test: 1.15.4
  mockito: 4.1.1