name: lazy_lumberdash
description: Lumberdash abstraction that lazily dispatches log calls, either periodically or stack size.
version: 0.0.2
author: freitzzz
homepage: https://github.com/freitzzz/lazy_lumberdash

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  lumberdash: ^3.0.0

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.16.6
  mocktail: